networks:
  camnet:
    driver: bridge

services:

  mediamtxui:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: ${PROJECT_NAME}
    container_name: ${PROJECT_NAME}
    working_dir: /app/server
    restart: unless-stopped
    command: 'node index.js'
    networks:
      - camnet
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "35729:35729"
    volumes:
      - /app/server/node_modules
      - .:/app
    environment:
      - DEBUG=true
      - VERBOSE=2
      - ENVIRONMENT=default
      - NODE_ENV=development
      - SERVER_PORT=${SERVER_PORT}
      - RTSP_PORT=${RTSP_PORT}
      - HLS_PORT=${HLS_PORT}
      - WEBRTC_PORT=${WEBRTC_PORT}
      - WEBRTC_UDP_PORT=${WEBRTC_UDP_PORT}
      - API_PORT=${API_PORT}
      - MEDIAMTX_API_URL_BASE=http://mediamtx:9997/v3
      - MEDIAMTX_METRICS_URL_BASE=http://mediamtx:9996/metrics
      - HW_ACCEL=${HW_ACCEL:-none}
      - RECORDING_PATH=/recordings
    devices:
      - '/dev/video0:/dev/video0'
      - '/dev/video1:/dev/video1'
      - '/dev/video2:/dev/video2'
      - '/dev/video3:/dev/video3'
      - '/dev/video4:/dev/video4'
      - '/dev/video5:/dev/video5'
      - '/dev/video10:/dev/video10'
      - '/dev/video11:/dev/video11'
    privileged: true
