import { useState } from 'react';

const REPO_URL = 'https://github.com/iamjairo/matter-onvif-bridge';

function loadConfig() {
  try {
    return JSON.parse(localStorage.getItem('matterbridge:config') || '{}');
  } catch {
    return {};
  }
}

function buildEnv(c) {
  const lines = [
    '# Generated by MediaMTX Dashboard',
    `ONVIF_USERNAME=${c.onvifUser || 'admin'}`,
    `ONVIF_PASSWORD=${c.onvifPass || '<set-me>'}`,
    `ONVIF_DISCOVERY_MODE=${c.discoveryMode || 'auto'}`,
  ];
  if (c.staticCameras) lines.push(`ONVIF_STATIC_CAMERAS=${c.staticCameras}`);
  if (c.cameraNames) lines.push(`ONVIF_CAMERA_NAMES=${c.cameraNames}`);
  lines.push('');
  lines.push(`MEDIA_SERVER=${c.mediaServer || 'mediamtx'}`);
  if ((c.mediaServer || 'mediamtx') === 'mediamtx') {
    lines.push(`MEDIAMTX_HOST=${c.mediaHost || 'localhost'}`);
    lines.push(`MEDIAMTX_API_PORT=${c.mediaPort || '9997'}`);
  } else {
    lines.push(`GO2RTC_HOST=${c.mediaHost || 'localhost'}`);
    lines.push(`GO2RTC_API_PORT=${c.mediaPort || '1984'}`);
  }
  return lines.join('\n');
}

function TextField({ label, fieldKey, placeholder, value, type = 'text', onChange }) {
  return (
    <div className="mbridge-field">
      <label>{label}</label>
      <input
        type={type}
        placeholder={placeholder}
        value={value}
        autoComplete="off"
        onChange={(e) => onChange(fieldKey, e.target.value)}
      />
    </div>
  );
}

function SelectField({ label, fieldKey, value, options, onChange }) {
  return (
    <div className="mbridge-field">
      <label>{label}</label>
      <select value={value} onChange={(e) => onChange(fieldKey, e.target.value)}>
        {options.map((o) => (
          <option key={o} value={o}>{o}</option>
        ))}
      </select>
    </div>
  );
}

export default function MatterBridgeTab() {
  const [config, setConfig] = useState(loadConfig);
  const [envOutput, setEnvOutput] = useState(null);
  const [copyLabel, setCopyLabel] = useState('Copy');

  function updateField(key, value) {
    setConfig((prev) => ({ ...prev, [key]: value }));
  }

  function saveConfig() {
    localStorage.setItem('matterbridge:config', JSON.stringify(config));
    console.warn('[MatterBridgeTab] Bridge configuration saved.');
  }

  function exportEnv() {
    setEnvOutput(buildEnv(config));
  }

  function copyEnv() {
    if (!envOutput) return;
    navigator.clipboard.writeText(envOutput).then(() => {
      setCopyLabel('Copied!');
      setTimeout(() => setCopyLabel('Copy'), 1500);
    });
  }

  return (
    <div className="tab matter-bridge-tab">
      {/* Header */}
      <div className="mbridge-header">
        <div className="mbridge-header-left">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--color-primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="m9 11-4 4 4 4M15 4l4 4-4 4" />
            <path d="m18 9-12 6" />
          </svg>
          <div>
            <h2>Matter Bridge</h2>
            <p>matter-onvif-bridge — expose ONVIF cameras as native Matter 1.5 devices for Google Home &amp; Apple Home</p>
          </div>
        </div>
        <div className="mbridge-header-right">
          <a href={REPO_URL} target="_blank" rel="noopener noreferrer" className="phase2-btn sm secondary">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ verticalAlign: '-2px', marginRight: '4px' }}>
              <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
            </svg>
            GitHub
          </a>
        </div>
      </div>

      {/* Runtime Status Card */}
      <section className="mbridge-card">
        <h3>Runtime Status</h3>
        <div className="mbridge-status-grid">
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Bridge Process</span>
            <span className="mbridge-stat-value" data-key="process">
              <span className="mbridge-dot off" />
              {' '}Not connected to dashboard
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Matter Port (5540/UDP)</span>
            <span className="mbridge-stat-value" data-key="matter-port">
              <span className="mbridge-dot unknown" />
              {' '}Unknown — checked from bridge host
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">ONVIF Discovery (3702/UDP)</span>
            <span className="mbridge-stat-value" data-key="onvif-port">
              <span className="mbridge-dot unknown" />
              {' '}Multicast — runs on bridge host
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Media Server</span>
            <span className="mbridge-stat-value" data-key="media">
              <span className="mbridge-dot on" />
              {' '}MediaMTX (this dashboard)
            </span>
          </div>
        </div>
        <p className="mbridge-note">
          The bridge runs as a separate Rust binary on a host with IPv6 + LAN multicast (typically not Docker on macOS).
          Live status would require the bridge to expose an HTTP API — see the{' '}
          <a href={`${REPO_URL}#roadmap`} target="_blank" rel="noopener noreferrer">roadmap</a> for tracking.
        </p>
      </section>

      {/* Configuration Card */}
      <section className="mbridge-card">
        <h3>Configuration</h3>
        <p className="mbridge-card-desc">
          These values are saved locally and used to generate a working <code>.env</code> file.
          They are not sent to the bridge automatically.
        </p>
        <div className="mbridge-form">
          <TextField label="ONVIF Username" fieldKey="onvifUser" placeholder="admin" value={config.onvifUser || 'admin'} onChange={updateField} />
          <TextField label="ONVIF Password" fieldKey="onvifPass" placeholder="••••••••" value={config.onvifPass || ''} type="password" onChange={updateField} />
          <SelectField label="Discovery Mode" fieldKey="discoveryMode" value={config.discoveryMode || 'auto'} options={['auto', 'static']} onChange={updateField} />
          <TextField label="Static Cameras (host:port,…)" fieldKey="staticCameras" placeholder="192.168.1.10:2020" value={config.staticCameras || ''} onChange={updateField} />
          <TextField label="Friendly Names (serial=name,…)" fieldKey="cameraNames" placeholder="ABC123=Front Door" value={config.cameraNames || ''} onChange={updateField} />
          <SelectField label="Media Server" fieldKey="mediaServer" value={config.mediaServer || 'mediamtx'} options={['mediamtx', 'go2rtc']} onChange={updateField} />
          <TextField label="Media Server Host" fieldKey="mediaHost" placeholder="localhost" value={config.mediaHost || 'localhost'} onChange={updateField} />
          <TextField label="Media Server API Port" fieldKey="mediaPort" placeholder="9997" value={config.mediaPort || '9997'} onChange={updateField} />
        </div>
        <div className="mbridge-form-actions">
          <button className="phase2-btn sm mbridge-save-btn" onClick={saveConfig}>Save</button>
          <button className="phase2-btn sm secondary mbridge-export-btn" onClick={exportEnv}>Export .env</button>
        </div>
        {envOutput !== null && (
          <div className="mbridge-env-output">
            <span className="mbridge-card-label">Generated .env</span>
            <pre className="mbridge-pre">{envOutput}</pre>
            <button className="phase2-btn sm secondary mbridge-copy-env-btn" onClick={copyEnv}>{copyLabel}</button>
          </div>
        )}
      </section>

      {/* Commissioning Card */}
      <section className="mbridge-card">
        <h3>Commissioning</h3>
        <p className="mbridge-card-desc">
          On first run the bridge prints a Matter pairing QR code to its console.
          Scan it with Google Home or Apple Home to add cameras as native Matter devices.
        </p>
        <div className="mbridge-commission">
          <div className="mbridge-qr-placeholder">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <rect x="3" y="3" width="7" height="7" />
              <rect x="14" y="3" width="7" height="7" />
              <rect x="3" y="14" width="7" height="7" />
              <path d="M14 14h7v7h-7z" />
            </svg>
            <span>QR code shown by bridge process</span>
          </div>
          <div className="mbridge-commission-info">
            <div className="mbridge-stat-line">
              <span>Vendor ID</span>
              <code>0xFFF1 (Test)</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Product ID</span>
              <code>0x8000</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Discriminator</span>
              <code>3840</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Setup PIN</span>
              <code>20202021 (default)</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Max Cameras</span>
              <code>8 endpoints (7 + motion, 1 video-only)</code>
            </div>
          </div>
        </div>
      </section>

      {/* Quick Start Card */}
      <section className="mbridge-card">
        <h3>Quick Start</h3>
        <div className="mbridge-quickstart-grid">
          <div>
            <span className="mbridge-card-label">1. Clone &amp; build</span>
            <pre className="mbridge-pre">{`git clone ${REPO_URL}
cd matter-onvif-bridge
cp .env.example .env
# edit .env with your ONVIF credentials
cargo run --release -p matter-onvif-bridge`}</pre>
          </div>
          <div>
            <span className="mbridge-card-label">2. Or use Docker (Linux)</span>
            <pre className="mbridge-pre">{`docker compose up -d
# host networking required for mDNS + ONVIF multicast`}</pre>
          </div>
        </div>
        <p className="mbridge-note">
          On macOS the bridge must run natively (Docker can't forward UDP multicast).
          Only the media server runs in Docker on macOS.
        </p>
      </section>
    </div>
  );
}
