import { useState } from 'react';

const REPO_URL = 'https://github.com/iamjairo/matter-onvif-bridge';

function loadConfig() {
  try {
    return JSON.parse(localStorage.getItem('matterbridge:config') || '{}');
  } catch {
    return {};
  }
}

function buildEnv(c) {
  const lines = [
    '# Generated by MediaMTX Dashboard',
    `ONVIF_USERNAME=${c.onvifUser || 'admin'}`,
    `ONVIF_PASSWORD=${c.onvifPass || '<set-me>'}`,
    `ONVIF_DISCOVERY_MODE=${c.discoveryMode || 'auto'}`,
  ];
  if (c.staticCameras) lines.push(`ONVIF_STATIC_CAMERAS=${c.staticCameras}`);
  if (c.cameraNames) lines.push(`ONVIF_CAMERA_NAMES=${c.cameraNames}`);
  lines.push('');
  lines.push(`MEDIA_SERVER=${c.mediaServer || 'mediamtx'}`);
  if ((c.mediaServer || 'mediamtx') === 'mediamtx') {
    lines.push(`MEDIAMTX_HOST=${c.mediaHost || 'localhost'}`);
    lines.push(`MEDIAMTX_API_PORT=${c.mediaPort || '9997'}`);
  } else {
    lines.push(`GO2RTC_HOST=${c.mediaHost || 'localhost'}`);
    lines.push(`GO2RTC_API_PORT=${c.mediaPort || '1984'}`);
  }
  return lines.join('\n');
}

function TextField({ label, fieldKey, placeholder, value, type = 'text', onChange }) {
  return (
    <div className="mbridge-field">
      <label>{label}</label>
      <input
        type={type}
        placeholder={placeholder}
        value={value}
        autoComplete="off"
        onChange={(e) => onChange(fieldKey, e.target.value)}
      />
    </div>
  );
}

function SelectField({ label, fieldKey, value, options, onChange }) {
  return (
    <div className="mbridge-field">
      <label>{label}</label>
      <select value={value} onChange={(e) => onChange(fieldKey, e.target.value)}>
        {options.map((o) => (
          <option key={o} value={o}>{o}</option>
        ))}
      </select>
    </div>
  );
}

export default function MatterBridgeTab() {
  const [config, setConfig] = useState(loadConfig);
  const [envOutput, setEnvOutput] = useState(null);
  const [copyLabel, setCopyLabel] = useState('Copy');

  function updateField(key, value) {
    setConfig((prev) => ({ ...prev, [key]: value }));
  }

  function saveConfig() {
    localStorage.setItem('matterbridge:config', JSON.stringify(config));
    console.warn('[MatterBridgeTab] Bridge configuration saved.');
  }

  function exportEnv() {
    setEnvOutput(buildEnv(config));
  }

  function copyEnv() {
    if (!envOutput) return;
    navigator.clipboard.writeText(envOutput).then(() => {
      setCopyLabel('Copied!');
      setTimeout(() => setCopyLabel('Copy'), 1500);
    });
  }

  return (
    <div className="tab matter-bridge-tab">
      {/* Header */}
      <div className="mbridge-header">
        <div className="mbridge-header-left">
          <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="var(--color-primary)" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="m9 11-4 4 4 4M15 4l4 4-4 4" />
            <path d="m18 9-12 6" />
          </svg>
          <div>
            <h2>Matter Bridge</h2>
            <p>matter-onvif-bridge — expose ONVIF cameras as native Matter 1.5 devices for Google Home &amp; Apple Home</p>
          </div>
        </div>
        <div className="mbridge-header-right">
          <a href={REPO_URL} target="_blank" rel="noopener noreferrer" className="phase2-btn sm secondary">
            <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" style={{ verticalAlign: '-2px', marginRight: '4px' }}>
              <path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22" />
            </svg>
            GitHub
          </a>
        </div>
      </div>

      {/* Capabilities — honest read of what's actually in the repo, not faked
          live status. The previous "Unknown / Multicast / Off" placeholder
          panel was removed because there's no bridge HTTP API to query yet;
          see the Roadmap card at the bottom for the planned control surface. */}
      <section className="mbridge-card">
        <h3>Capabilities</h3>
        <p className="mbridge-card-desc">
          What the bridge ships today, pulled from <code>ROADMAP.md</code> + the matter-camera crate.
          Matter 1.5 clusters · media-server choice · OccupancySensing for motion.
        </p>
        <div className="mbridge-status-grid">
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Matter 1.5 clusters</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot on" />
              {' '}10 implemented (6 functional, 2 stub, 2 inherited)
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Media-server support</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot on" />
              {' '}go2rtc 1.9.7 · MediaMTX 1.12.2 (both pinned)
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Max endpoints</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot on" />
              {' '}8 cameras (7 + motion, 1 video-only)
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Test coverage</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot on" />
              {' '}47 passing · clippy clean · fmt clean
            </span>
          </div>
        </div>
        <div className="mbridge-cluster-list">
          <span className="mbridge-card-label">Implemented Matter 1.5 clusters</span>
          <div className="mbridge-stat-line"><span>CameraAvStreamManagement</span><code>0x0551 · functional</code></div>
          <div className="mbridge-stat-line"><span>WebRTCTransportProvider</span><code>0x0553 · functional</code></div>
          <div className="mbridge-stat-line"><span>WebRTCTransportRequestor</span><code>0x0554 · functional</code></div>
          <div className="mbridge-stat-line"><span>ZoneManagement</span><code>0x0550 · in-memory CRUD</code></div>
          <div className="mbridge-stat-line"><span>OccupancySensing</span><code>0x0406 · motion via ONVIF MotionAlarm</code></div>
          <div className="mbridge-stat-line"><span>PushAvStreamTransport</span><code>0x0555 · stub</code></div>
          <div className="mbridge-stat-line"><span>Chime</span><code>0x0556 · stub</code></div>
        </div>
      </section>

      {/* Numbered setup wizard — Step 1 / Configure */}
      <section className="mbridge-card mbridge-step">
        <h3><span className="mbridge-step-num">1</span> Configure</h3>
        <p className="mbridge-card-desc">
          These values are saved locally and used to generate a working <code>.env</code> file.
          They are not sent to the bridge automatically — the bridge reads its own <code>.env</code> at startup.
        </p>
        <div className="mbridge-form">
          <TextField label="ONVIF Username" fieldKey="onvifUser" placeholder="admin" value={config.onvifUser || 'admin'} onChange={updateField} />
          <TextField label="ONVIF Password" fieldKey="onvifPass" placeholder="••••••••" value={config.onvifPass || ''} type="password" onChange={updateField} />
          <SelectField label="Discovery Mode" fieldKey="discoveryMode" value={config.discoveryMode || 'auto'} options={['auto', 'static']} onChange={updateField} />
          <TextField label="Static Cameras (host:port,…)" fieldKey="staticCameras" placeholder="192.168.1.10:2020" value={config.staticCameras || ''} onChange={updateField} />
          <TextField label="Friendly Names (serial=name,…)" fieldKey="cameraNames" placeholder="ABC123=Front Door" value={config.cameraNames || ''} onChange={updateField} />
          <SelectField label="Media Server" fieldKey="mediaServer" value={config.mediaServer || 'mediamtx'} options={['mediamtx', 'go2rtc']} onChange={updateField} />
          <TextField label="Media Server Host" fieldKey="mediaHost" placeholder="localhost" value={config.mediaHost || 'localhost'} onChange={updateField} />
          <TextField label="Media Server API Port" fieldKey="mediaPort" placeholder="9997" value={config.mediaPort || '9997'} onChange={updateField} />
        </div>
        <div className="mbridge-form-actions">
          <button className="phase2-btn sm mbridge-save-btn" onClick={saveConfig}>Save</button>
          <button className="phase2-btn sm secondary mbridge-export-btn" onClick={exportEnv}>Export .env</button>
        </div>
        {envOutput !== null && (
          <div className="mbridge-env-output">
            <span className="mbridge-card-label">Generated .env</span>
            <pre className="mbridge-pre">{envOutput}</pre>
            <button className="phase2-btn sm secondary mbridge-copy-env-btn" onClick={copyEnv}>{copyLabel}</button>
          </div>
        )}
      </section>

      {/* Step 2 — Deploy snippets. Pulled from README quickstart so this stays
          in sync with the canonical install paths. */}
      <section className="mbridge-card mbridge-step">
        <h3><span className="mbridge-step-num">2</span> Deploy</h3>
        <p className="mbridge-card-desc">
          Three supported paths. macOS must run native (Docker can't forward UDP multicast for ONVIF discovery / Matter mDNS).
        </p>
        <div className="mbridge-quickstart-grid">
          <div>
            <span className="mbridge-card-label">Native (macOS / Linux)</span>
            <pre className="mbridge-pre">{`git clone ${REPO_URL}
cd matter-onvif-bridge
cp .env.example .env
# edit .env with your ONVIF credentials, then:
cargo run --release -p matter-onvif-bridge`}</pre>
          </div>
          <div>
            <span className="mbridge-card-label">Docker Compose (Linux only)</span>
            <pre className="mbridge-pre">{`docker compose up -d
# requires host networking for mDNS + ONVIF multicast`}</pre>
          </div>
          <div>
            <span className="mbridge-card-label">systemd (Raspberry Pi / Linux server)</span>
            <pre className="mbridge-pre">{`./scripts/install-service.sh
# installs binary + .env to /opt and enables matter-onvif-bridge.service`}</pre>
          </div>
        </div>
        <p className="mbridge-note">
          External drives don't support incremental compilation locks — set <code>CARGO_INCREMENTAL=0</code> when building from one.
        </p>
      </section>

      {/* Step 3 — Commissioning */}
      <section className="mbridge-card mbridge-step">
        <h3><span className="mbridge-step-num">3</span> Commission</h3>
        <p className="mbridge-card-desc">
          On first run the bridge prints a Matter pairing QR code to its console.
          Scan it with Google Home or Apple Home to add cameras as native Matter devices.
          Once paired, the bridge persists endpoint slots so room assignments survive restarts.
        </p>
        <div className="mbridge-commission">
          <div className="mbridge-qr-placeholder">
            <svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <rect x="3" y="3" width="7" height="7" />
              <rect x="14" y="3" width="7" height="7" />
              <rect x="3" y="14" width="7" height="7" />
              <path d="M14 14h7v7h-7z" />
            </svg>
            <span>QR code shown by bridge process</span>
          </div>
          <div className="mbridge-commission-info">
            <div className="mbridge-stat-line">
              <span>Vendor ID</span>
              <code>0xFFF1 (Test)</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Product ID</span>
              <code>0x8000</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Discriminator</span>
              <code>3840</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Setup PIN</span>
              <code>20202021 (default)</code>
            </div>
            <div className="mbridge-stat-line">
              <span>Max Cameras</span>
              <code>8 endpoints (7 + motion, 1 video-only)</code>
            </div>
          </div>
        </div>
      </section>

      {/* Step 4 — Verify in a real Matter controller. Replaces the "Quick Start"
          card; controller validation is the immediate roadmap priority and
          tracking it in-tab gives the user a place to record results. */}
      <section className="mbridge-card mbridge-step">
        <h3><span className="mbridge-step-num">4</span> Verify in a Matter controller</h3>
        <p className="mbridge-card-desc">
          After commissioning, walk the camera through the basics in each ecosystem you use.
          The README's tested-controller matrix will be updated as results come in.
        </p>
        <div className="mbridge-status-grid">
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Google Home</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}Not yet validated · live view + motion target
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Apple Home</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}Not yet validated · live view target
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">Amazon Alexa</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}Not yet validated · stretch target
            </span>
          </div>
        </div>
        <p className="mbridge-note">
          Verification checklist per controller: <strong>commissioning succeeds</strong> · <strong>live view streams</strong> · <strong>motion event fires</strong> · <strong>device survives restart</strong>.
        </p>
      </section>

      {/* Roadmap callout — live status / control surface is the next major
          bridge feature. This card replaces the dishonest status panel that
          previously claimed to show port states it couldn't actually read. */}
      <section className="mbridge-card mbridge-roadmap">
        <h3>Live status — coming soon</h3>
        <p className="mbridge-card-desc">
          The bridge currently has no HTTP API, so this tab can't show real-time process /
          camera / motion state. An Axum control surface is being designed:
        </p>
        <div className="mbridge-status-grid">
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">GET /api/status</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}bridge health, discovery mode, last scan
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">GET /api/cameras</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}discovered + commissioned, endpoint IDs, motion state
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">GET /api/pairing/qr</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}commissioning QR PNG (when in commissioning window)
            </span>
          </div>
          <div className="mbridge-stat">
            <span className="mbridge-stat-label">GET /api/events (SSE)</span>
            <span className="mbridge-stat-value">
              <span className="mbridge-dot unknown" />
              {' '}live motion / discovery / commissioning event stream
            </span>
          </div>
        </div>
        <p className="mbridge-note">
          See <a href={`${REPO_URL}/blob/main/ROADMAP.md`} target="_blank" rel="noopener noreferrer">ROADMAP.md</a> for sequencing — controller validation lands first, then the control surface.
        </p>
      </section>
    </div>
  );
}
